### ISSUE TITLE
wget download the langchain docs failed

### ISSUE THREAD

**Issue by Bruce-CodeMan** [emarco177/documentation-helper#1]
I tried your code "wget -r -A.html -P langchain-docs https://langchain.readthedocs.io/en/latest/" to download the langchain-docs, I always failed 
<img width="750" alt="微信截图_20230509215932" src="https://github.com/emarco177/documentation-helper/assets/65518559/5fa8eee8-a1b3-4a05-96bf-3930a8f870f8">

**Comment by emarco177** [comment]
changed the url to:
https://python.langchain.com/en/latest/index.html

and this should resolve it

**Comment by anuraagdjain** [comment]
@emarco177  A minor nit. Could you push the change in path for `ingestion.py`? Since the domain is changed, the folder also is different. 

```python
loader = ReadTheDocsLoader("langchain-docs/python.langchain.com/en/latest")
```

**Comment by emarco177** [comment]
Done thanks!
